input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  # You can add geoip or further parsing here later
  mutate {
    add_tag => [ "windows_ids_event" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "ids-alerts-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
