input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    add_tag => [ "docker_ids_sensor" ]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"] 
    index => "windows-ids-logs"
  }
  stdout { codec => rubydebug }
}
